export class Movie {
  public title: string;
  public year: string;
  public rated: string;
  public released: string;
  public runtime: string;
  public genre: string;
  public director: string;
  public writer: string;
  public actors: string;
  public plot: string;
  public language: string;
  public country: string;
  public awards: string;
  public poster: string;
  public ratings: any[];
  public metascore: string;
  public imdbRating: string;
  public imdbVotes: string;
  public imdbID: string;
  public type: string;
  public DVD: string;
  public boxOffice: string;
  public production: string;
  public website: string;
  public response: string;

  constructor(movieData: any) {
    this.title = movieData.Title;
    this.year = movieData.Year;
    this.rated = movieData.Rated;
    this.released = movieData.Released;
    this.runtime = movieData.Runtime;
    this.genre = movieData.Genre;
    this.director = movieData.Director;
    this.writer = movieData.Writer;
    this.actors = movieData.Actors;
    this.plot = movieData.Plot;
    this.language = movieData.Language;
    this.country = movieData.Country;
    this.awards = movieData.Awards;
    this.poster = movieData.Poster;
    this.ratings = movieData.Ratings;
    this.metascore = movieData.Metascore;
    this.imdbRating = movieData.imdbRating;
    this.imdbVotes = movieData.imdbVotes;
    this.imdbID = movieData.imdbID;
    this.type = movieData.Type;
    this.DVD = movieData.DVD;
    this.boxOffice = movieData.BoxOffice;
    this.production = movieData.Production;
    this.website = movieData.Website;
    this.response = movieData.Response;
  }
}
