export class Movie {
  public Title: string;
  public Year: string;
  public Rated: string;
  public Released: string;
  public Runtime: string;
  public Genre: string;
  public Director: string;
  public Writer: string;
  public Actors: string;
  public Plot: string;
  public Language: string;
  public Country: string;
  public Awards: string;
  public Poster: string;
  public Ratings: any[];
  public Metascore: string;
  public ImdbRating: string;
  public ImdbVotes: string;
  public ImdbID: string;
  public Type: string;
  public DVD: string;
  public BoxOffice: string;
  public Production: string;
  public Website: string;
  public Response: string;

  constructor(movieData: any) {
    this.Title = movieData.Title;
    this.Year = movieData.Year;
    this.Rated = movieData.Rated;
    this.Released = movieData.Released;
    this.Runtime = movieData.Runtime;
    this.Genre = movieData.Genre;
    this.Director = movieData.Director;
    this.Writer = movieData.Writer;
    this.Actors = movieData.Actors;
    this.Plot = movieData.Plot;
    this.Language = movieData.Language;
    this.Country = movieData.Country;
    this.Awards = movieData.Awards;
    this.Poster = movieData.Poster;
    this.Ratings = movieData.Ratings;
    this.Metascore = movieData.Metascore;
    this.ImdbRating = movieData.imdbRating;
    this.ImdbVotes = movieData.imdbVotes;
    this.ImdbID = movieData.imdbID;
    this.Type = movieData.Type;
    this.DVD = movieData.DVD;
    this.BoxOffice = movieData.BoxOffice;
    this.Production = movieData.Production;
    this.Website = movieData.Website;
    this.Response = movieData.Response;
  }
}
